version: '3.4'
services:
  ritmic-server:
    container_name: ritmic-server
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    environment:
      - VUE_APP_DATABASE_URI=mongodb://server-db
    ports:
      - 3003:3003
    depends_on: 
      - server-db
    links:
      - server-db
    networks:
    - ritmic_net

  server-db:
    image: mongo
    container_name: server-db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=ritmic
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      # seeding scripts
      - ./server/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
    - ritmic_net

  ritmic-app:
    container_name: ritmic-app
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    ports:
      - 8080:8080
    depends_on:
      - ritmic-server
    links:
      - ritmic-server
    networks:
    - ritmic_net

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:

networks:
  ritmic_net:
    driver: bridge
