FROM node:12.16

RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        netcat \
    && apt-get -q clean

RUN mkdir -p /usr/src/ritmic/server

WORKDIR /usr/src/ritmic/server

ENV PATH /usr/src/ritmic/server/node_modules/.bin:$PATH

COPY . /usr/src/ritmic/server

RUN npm install --silent

CMD ["./entrypoint.sh"]